# Generated by Django 2.2.12 on 2020-07-04 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artha.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('lecture', models.FileField(default='', upload_to='lectures')),
                ('video_title', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artha.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_paced', models.CharField(max_length=500)),
                ('intructor_lead', models.CharField(max_length=500)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artha.Courses')),
            ],
        ),
    ]
