# Generated by Django 2.2.12 on 2020-07-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor_name',
        ),
    ]
