# Generated by Django 2.2.12 on 2020-07-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artha', '0003_auto_20200710_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artha.Courses'),
        ),
    ]
