# Generated by Django 2.2.12 on 2020-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artha', '0004_subject_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='standard',
        ),
    ]
