# Generated by Django 2.2.12 on 2020-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artha', '0005_auto_20200710_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='standard',
            field=models.CharField(default='', max_length=60),
        ),
    ]
