# Generated by Django 2.2.12 on 2020-07-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artha', '0007_remove_courses_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='std',
            field=models.CharField(default='', max_length=60),
        ),
    ]
