# Generated by Django 2.2.12 on 2020-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='standard',
            field=models.CharField(default='', max_length=30, verbose_name='standard'),
        ),
    ]
